[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "sherlock-project"
version = "0.16.0"
description = "Hunt down social media accounts by username across social networks"
license = {text = "MIT"}
authors = [
    {name = "Siddharth Dushantha", email = "siddharth.dushantha@gmail.com"}
]
maintainers = [
    {name = "Paul Pfeister", email = "code@pfeister.dev"},
    {name = "Matheus Felipe", email = "matheusfelipeog@protonmail.com"},
    {name = "Sondre Karlsen Dyrnes", email = "sondre@villdyr.no"}
]
readme = "docs/pyproject/README.md"
keywords = ["osint", "reconnaissance", "information gathering"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Intended Audience :: Information Technology",
    "License :: OSI Approved :: MIT License",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Security"
]
requires-python = ">=3.9"
dependencies = [
    "certifi>=2019.6.16",
    "colorama>=0.4.1,<0.5",
    "PySocks>=1.7.0,<2",
    "requests>=2.22.0,<3",
    "requests-futures>=1.0.0,<2",
    "stem>=1.8.0,<2",
    "pandas>=2.2.1,<3",
    "openpyxl>=3.0.10,<4",
    "tomli>=2.2.1,<3"
]

[project.optional-dependencies]
dev = [
    "jsonschema>=4.0.0,<5",
    "rstr>=3.2.2,<4",
    "pytest>=8.4.2,<9",
    "pytest-xdist>=3.8.0,<4",
    "ruff",
    "pytest",
    "coverage"
]
ci = [
    "defusedxml>=0.7.1,<0.8"
]

[project.urls]
Homepage = "https://sherlockproject.xyz/"
Repository = "https://github.com/sherlock-project/sherlock"
"Bug Tracker" = "https://github.com/sherlock-project/sherlock/issues"

[project.scripts]
sherlock = "sherlock_project.sherlock:main"

[tool.hatch.build.targets.wheel]
packages = ["sherlock_project"]
